name: PHPUnit Tests

on:
    push:
    pull_request:
    release:
        types:
            - published

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
        laravel: [ 7.*, 8.*, 9.* ]
        include:
          - php: 8.1
            laravel: 9.*
        exclude:
          - php: 7.4
            laravel: 9.*

    name: '[PHP ${{ matrix.php }}] [Laravel ${{ matrix.laravel }}]'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring json openssl
          ini-values: memory_limit=-1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-${{ hashFiles('**/composer.json') }}"

      - name: Install composer packages
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-progress --no-update
          composer update --no-progress --prefer-dist --no-interaction --no-suggest
          composer install --no-progress --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit --colors=always